Support Gitlab SCM data - F2600026
MicroFocus/octane-ci-java-sdk pull request #234
Opened 2024-09-12 14:23 UTC by andreibangau99

2024-09-12 14:28 UTC, andreibangau99 commented on integrations-sdk/src/main/java/com/hp/octane/integrations/services/pullrequestsandbranches/PullRequestAndBranchServiceImpl.java
> +                                                .collect(Collectors.toSet())
Maybe checking only by the last commit would be enough

2024-09-13 10:29 UTC, LauraBuzas submitted a review, later dismissed

2024-09-15 09:21 UTC, nissimshitrit requested changes

2024-09-15 09:21 UTC, nissimshitrit commented on integrations-sdk/src/main/java/com/hp/octane/integrations/services/pullrequestsandbranches/PullRequestAndBranchServiceImpl.java
> +                    .collect(Collectors.toList());
You should create those two maps outside the stream since it might execute per iteration and might effect prefomnece
you should set them separately then use it inside the stream

2024-09-15 09:21 UTC, nissimshitrit commented on integrations-sdk/src/main/java/com/hp/octane/integrations/services/pullrequestsandbranches/gitlab/JsonConverter.java
> +            //do nothing
please add here at least some log that some error happened

2024-09-16 11:33 UTC, nissimshitrit approved these changes

2024-09-16 11:55 UTC, merged